### ISSUE TITLE
I am reminding No module named "rlgraph.envs" when running rlgraph.py in win10 pycharm environment.

### ISSUE THREAD

**Issue by Miulei** [reinforceio/tensorforce-benchmark#5]
When installing rlgraph.envs with pip, the prompt is Could not find a version that satisfies the requirement rlgraph.envs (from versions: ) No matching distribution found for rlgraph.envs
who knows why?

**Comment by michaelschaarschmidt** [comment]
Envs got renamed to Environments I think, needs to be updated, cc @krfricke

**Comment by Miulei** [comment]
> Envs got renamed to Environments I think, needs to be updated, cc @krfricke

How can I update?

**Comment by michaelschaarschmidt** [comment]
Sorry, I meant we have to update this.

**Comment by Miulei** [comment]
> Sorry, I meant we have to update this

Thank you, when are you going to update, I just started to learn this, there are many places that I don't understand?

**Comment by Miulei** [comment]
> Sorry, I meant we have to update this.

"rlgraph.evns" Is this module invalid? Why can't I install with pip?

**Comment by Miulei** [comment]
> Sorry, I meant we have to update this.

May I ask a simple question? What is the OpenAI gym ID? Is the algorithm name or the name of the game?

**Comment by krfricke** [comment]
`pip install -e .` worked for me on a clean virtualenv without any further changes. I updated the references to `rlgraph.environments` anyway and uploaded a new version to pypi. 

If the problem persists, please provide the command you used for installation and the full error output.

**Comment by Miulei** [comment]
> `pip install -e .` worked for me on a clean virtualenv without any further changes. I updated the references to `rlgraph.environments` anyway and uploaded a new version to pypi.
> 
> If the problem persists, please provide the command you used for installation and the full error output.

Traceback (most recent call last):
  File "scripts\benchmark_gym.py", line 214, in <module>
    sys.exit(main())
  File "scripts\benchmark_gym.py", line 182, in main
    save_model_file=args.model
  File "D:\python\PyCharm 2018.2.4\demo\rl-benchmark-master\rl_benchmark\benchmark\runner\benchmark_runner.py", line 252, in run
    results = self.run_experiment(environment, i)
  File "D:\python\PyCharm 2018.2.4\demo\rl-benchmark-master\rl_benchmark\libraries\rlgraph.py", line 108, in run_experiment
    action_space=environment.action_space,
  File "D:\python\anaconda\envs\py35\lib\site-packages\rlgraph\utils\specifiable.py", line 156, in from_spec
    obj = constructor(*ctor_args, **ctor_kwargs)
TypeError: __init__() missing 1 required positional argument: 'clip_ratio'

**Comment by Miulei** [comment]
I installed the updated rlgraph-0.1.1-py3-none-any.whl. After the benchmark.py file is loaded, run python scripts\benchmark_gym.py configs\tensorforce\ppo_cartpole.json CartPole-v0.
Prompt above typeError

**Comment by Miulei** [comment]
1. Excuse me about python scripts/benchmark_gym.py [--output output] [--experiments num_experiments] [--append] [--model <path>] [--save-model <num_episodes>] [- -load-model <path>] [--history <file>] [--history-episodes <num_episodes>] [--load-history <file>] [--rl_library rl_library] <algorithm> <gym_id> Give a specific column, such as the path format of -o OUTPUT.
2. How to set the format of the input file in Analyzing benchmarks?

**Comment by Miulei** [comment]
When I execute >python scripts\benchmark_gym.py -D -P -R rlgraph -o D:\python\ppo.pkl -l None -H None -L D:\python\PyCharm 2018.2.4\demo\rl-benchmark- Master configs\tensorforce\ppo_cartpole.json  CartPole-v0。
The following error occurred ：benchmark_gym.py: error: unrecognized arguments: CartPole-v0

**Comment by krfricke** [comment]
You're trying to use a tensorforce config for the RLgraph library. This does not work. Please use `-R tensorforce` instead and it should work (it worked for me with `python3 scripts/benchmark_gym.py -D -P -R tensorforce configs/tensorforce/ppo_cartpole.json CartPole-v0`).

Please also note that we're in the progress of including the RLgraph library to the benchmark library. As of now, benchmarking RLgraph is not supported, yet.

**Comment by Miulei** [comment]
I used your method to download the latest rlgraph from Pypi, but the problem persists.

D:\python\PyCharm 2018.2.4\demo\rl-benchmark-master>python scripts/benchmark_gym.py -D -P -R tensorforce configs/tensorforce/ppo_cartpole.json CartPole-v0
Traceback (most recent call last):
  File "scripts/benchmark_gym.py", line 87, in <module>
    from rl_benchmark.libraries import libraries
  File "D:\python\PyCharm 2018.2.4\demo\rl-benchmark-master\rl_benchmark\libraries\__init__.py", line 20, in <module>
    from rl_benchmark.libraries.rlgraph import RLgraphBenchmarkRunner
  File "D:\python\PyCharm 2018.2.4\demo\rl-benchmark-master\rl_benchmark\libraries\rlgraph.py", line 36, in <module>
    from rlgraph.envs import OpenAIGymEnv
ImportError: No module named 'rlgraph.envs'

When I changed the from rlgraph.envs import OpenAIGymEnv in rlgraph.py to from rlgraph. environments import OpenAIGym, when there is no input parameter that can be ignored, for example: -o output has the following problem：
D:\python\PyCharm 2018.2.4\demo\rl-benchmark-master>python scripts/benchmark_gym.py -D -P -R tensorforce configs/tensorforce/ppo_cartpole.json CartPole-v0
Traceback (most recent call last):
  File "scripts/benchmark_gym.py", line 214, in <module>
    sys.exit(main())
  File "scripts/benchmark_gym.py", line 150, in main
    if args.output:
AttributeError: 'Namespace' object has no attribute 'output'

**Comment by Miulei** [comment]
I am using window10 system and pycharm, python version is python3.5

**Comment by krfricke** [comment]
The `rlgraph.environments` issue has been fixed in the current master. Please update to the current version.
For te second problem, did you remove the output parameter line? The error never occurs for me. In fact, the very command works fine for me:

```
$ python3 scripts/benchmark_gym.py -D -P -R tensorforce configs/tensorforce/ppo_cartpole.json CartPole-v0
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Experiment 1:   0%|                                                                                                                                                                                                                                     | 0/500 [00:00<?, ?it/s]INFO:tensorflow:Graph was finalized.
18-10-23 20:31:28:INFO:Graph was finalized.
2018-10-23 20:31:28.715271: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Running local_init_op.
18-10-23 20:31:29:INFO:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
18-10-23 20:31:29:INFO:Done running local_init_op.
Experiment 1:  13%|███████████████████████▋            
```

**Comment by Miulei** [comment]
I have updated the latest source files and followed the steps you gave, but the following error still occurred.
D:\python\PyCharm 2018.2.4\demo\rl-benchmark-master\rl-benchmark-master>python scripts/benchmark_gym.py -D -P -R tensorforce configs/tensorforce/ppo_cartpole.json CartPole-v0
Traceback (most recent call last):
  File "scripts/benchmark_gym.py", line 214, in <module>
    sys.exit(main())
  File "scripts/benchmark_gym.py", line 150, in main
    if args.output:
AttributeError: 'Namespace' object has no attribute 'output'

Do you consider whether the following benchmark.py can really ignore these parameters when calling these parameters? Ignore will always prompt AttributeError: 'Namespace' object has no attribute "xxx"

**Comment by Miulei** [comment]
I changed the ubuntu16.04 and ran it. The following error occurred.

Experiment 1: 100%|▉| 498/500 [00:58<00:00,  6.98it/s, R=200, AR100=188.85, AR50Experiment 1: 100%|▉| 498/500 [00:58<00:00,  6.98it/s, R=195, AR100=188.80, AR50Experiment 1: 100%|▉| 499/500 [00:58<00:00,  6.80it/s, R=195, AR100=188.80, AR50Experiment 1: 100%|▉| 499/500 [00:58<00:00,  6.80it/s, R=200, AR100=188.80, AR50Experiment 1: 100%|█| 500/500 [00:58<00:00,  6.85it/s, R=200, AR100=188.80, AR50Experiment 1: 100%|█| 500/500 [00:58<00:00,  6.85it/s, R=200, AR100=188.80, AR500=117.66]
18-10-24 18:17:55:WARNING:No config file found, using default config...
Traceback (most recent call last):
  File "scripts/benchmark_gym.py", line 214, in <module>
    sys.exit(main())
  File "scripts/benchmark_gym.py", line 199, in main
    save_info = benchmark_runner.save_results_db(db=web_db)
  File "//home/o110/rl-benchmark-master/rl-benchmark-master/rl_benchmark/benchmark/runner/benchmark_runner.py", line 291, in save_results_db
    return db.save_benchmark(benchmark_data)
  File "//home/o110/rl-benchmark-master/rl-benchmark-master/rl_benchmark/db/web_db.py", line 74, in save_benchmark
    result = self.call_api('/experiment', method='post', json=benchmark_data)
  File "//home/o110/rl-benchmark-master/rl-benchmark-master/rl_benchmark/db/web_db.py", line 86, in call_api
    target_url = urllib.urljoin(self.url, API_VERSION + endpoint)
AttributeError: module 'six.moves.urllib' has no attribute 'urljoin'

**Comment by krfricke** [comment]
There's definitely something wrong with your setup. Those errors seem to stem from outdated argparse and six modules. Please create a new fresh virtualenvironment, preferably with python 3.6.6, and install tensorflow, tensorforce, this library and the dependencies from scratch.

**Comment by Miulei** [comment]
I reconfigured the virtual environment and re-downloaded the various dependencies with python 3.6.6, but the above problem still exists? I don't know what to do? Can you send me the detailed configuration of your environment?

**Comment by krfricke** [comment]
```
.$ cd rl-benchmark/
./rl-benchmark$ pyenv virtualenv 3.6.7 test
Looking in links: /tmp/tmpptx3223x
Requirement already satisfied: setuptools in /data/kai/home/.pyenv/versions/3.6.7/envs/test/lib/python3.6/site-packages (39.0.1)
Requirement already satisfied: pip in /data/kai/home/.pyenv/versions/3.6.7/envs/test/lib/python3.6/site-packages (10.0.1)
./rl-benchmark$ pyenv activate test
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
(test) ./rl-benchmark$ pip install -e .
Obtaining file:///data/coding/rlcore/rl-benchmark
# ...
Successfully installed argcomplete-1.9.4 arghandler-1.2.0 atomicwrites-1.2.1 attrs-18.2.0 certifi-2018.10.15 chardet-3.0.4 idna-2.7 more-itertools-4.3.0 numpy-1.15.3 pillow-5.3.0 pluggy-0.8.0 py-1.7.0 pytest-3.9.2 pyyaml-3.13 requests-2.20.0 rl-benchmark scipy-1.1.0 six-1.11.0 tensorforce-0.4.3 tqdm-4.28.1 urllib3-1.24
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test) ./rl-benchmark$ pip install tensorflow
Collecting tensorflow
# ...
Successfully installed absl-py-0.6.1 astor-0.7.1 gast-0.2.0 grpcio-1.16.0 h5py-2.8.0 keras-applications-1.0.6 keras-preprocessing-1.0.5 markdown-3.0.1 protobuf-3.6.1 tensorboard-1.11.0 tensorflow-1.11.0 termcolor-1.1.0 werkzeug-0.14.1 wheel-0.32.2
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test) ./rl-benchmark$ pip install rlgraph
Collecting rlgraph
# ...
Successfully installed opencv-python-3.4.3.18 rlgraph-0.1.1
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test) ./rl-benchmark$ pip install gym
Collecting gym
# ...
Installing collected packages: future, pyglet, gym
Successfully installed future-0.17.0 gym-0.10.8 pyglet-1.3.2
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test) ./rl-benchmark$ python scripts/benchmark_gym.py -D -P -R tensorforce configs/tensorforce/ppo_cartpole.json CartPole-v0
Experiment 1:   0%|                                                                                                                                                      | 0/500 [00:00<?, ?it/s]INFO:tensorflow:Graph was finalized.
18-10-27 15:12:28:INFO:Graph was finalized.
2018-10-27 15:12:28.896167: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Running local_init_op.
18-10-27 15:12:29:INFO:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
18-10-27 15:12:29:INFO:Done running local_init_op.
Experiment 1:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 494/500 [00:54<00:00,  6.99it/s, R=164, AR100=173.20, AR500=100.79]^C
# usually learns to 200
```
